// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2017.RI3D;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.VictorSP;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainRightMotor2;
    public static SpeedController driveTrainRightMotor1;
    public static SpeedController driveTrainLeftMotor2;
    public static SpeedController driveTrainLeftMotor1;
    public static RobotDrive driveTrainRobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainRightMotor2 = new VictorSP(2);
        LiveWindow.addActuator("DriveTrain", "RightMotor2", (VictorSP) driveTrainRightMotor2);
        
        driveTrainRightMotor1 = new VictorSP(3);
        LiveWindow.addActuator("DriveTrain", "RightMotor1", (VictorSP) driveTrainRightMotor1);
        
        driveTrainLeftMotor2 = new VictorSP(1);
        LiveWindow.addActuator("DriveTrain", "LeftMotor2", (VictorSP) driveTrainLeftMotor2);
        
        driveTrainLeftMotor1 = new VictorSP(0);
        LiveWindow.addActuator("DriveTrain", "LeftMotor1", (VictorSP) driveTrainLeftMotor1);
        
        driveTrainRobotDrive = new RobotDrive(driveTrainLeftMotor1, driveTrainLeftMotor2,
              driveTrainRightMotor2, driveTrainRightMotor1);
        
        driveTrainRobotDrive.setSafetyEnabled(true);
        driveTrainRobotDrive.setExpiration(0.1);
        driveTrainRobotDrive.setSensitivity(0.5);
        driveTrainRobotDrive.setMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
